spring.application.name=coding-arena

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/coding_arena
spring.datasource.username=arena
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# External APIs
judge0.api.url=https://ce.judge0.com

# Run data.sql after Hibernate creates the tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true